### PR TITLE
Fix for Syntax error near line 34

### PR DESCRIPTION
**Pull request by StephenShamakian**
Square brackets were used in the bash if condition when round brackets (parentheses) should have been used.

This is also a fix for this issue: #4

### CODE REVIEW

**Comment by thiagocrepaldi** [comment]
@StephenShamakian is the issue still there?

**Comment by StephenShamakian** [comment]
> @StephenShamakian is the issue still there?

Funny you mention it! I just recently re-forked this to add `-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null` to the SCP command (https://github.com/thiagocrepaldi/homelab-utility-belt/compare/main...StephenShamakian:homelab-utility-belt:main) as I had to rebuild my pfSense router recently and I didn't want to also have to update the known host keys on the various NAS devices I have after doing that.

But I left the square brackets in this time and it seems to be working now. So I'm not sure why it was failing on them in the past.

**Comment by thiagocrepaldi** [comment]
indeed funny, maybe a different version of pfsense which had a different version shell? I use these scripts on my own setup, so they should work or I would notice.

**Comment by StephenShamakian** [comment]
The problem (if I am remembering correctly) was a syntax issue on this line: https://github.com/thiagocrepaldi/homelab-utility-belt/blob/main/synology/install_letsencrypt_cert_from_pfsense.sh#L34

When I changed the square brackets to parentheses it fixed the issue.

I'm pretty sure this code runs on the Synology as a scheduled task not the pfSense box. I'm wondering if something changed with the version of shell in DSM possibly since the original issue?

**Pull request closed without merging**
